name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure this matches your branch name (main or master)

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v4

      - name: Inject Secrets into main.js üíâ
        run: |
          sed -i "s|__FIREBASE_API_KEY__|${{ secrets.FIREBASE_API_KEY }}|g" js/main.js
          sed -i "s|__FIREBASE_AUTH_DOMAIN__|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" js/main.js
          sed -i "s|__FIREBASE_PROJECT_ID__|${{ secrets.FIREBASE_PROJECT_ID }}|g" js/main.js
          sed -i "s|__STORAGEBUCKET__|${{ secrets.STORAGEBUCKET }}|g" js/main.js
          sed -i "s|__MESSAGINGSENDERID__|${{ secrets.MESSAGINGSENDERID }}|g" js/main.js
          sed -i "s|__FIREBASE_APP_ID__|${{ secrets.FIREBASE_APP_ID }}|g" js/main.js
          sed -i "s|__MEASUREMENTID__|${{ secrets.MEASUREMENTID }}|g" js/main.js

      - name: Deploy üöÄ
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder the action should deploy.
          branch: gh-pages # The branch the action should deploy to.