name: Deploy Website

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  inject-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Inject Secrets ðŸ’‰
        run: |
          # Targeting ONLY the specific config file
          FILE="js/firebase-config.js"
          sed -i "s|GH_INJECT_API_KEY|${{ secrets.FIREBASE_API_KEY }}|g" $FILE
          sed -i "s|GH_INJECT_AUTH_DOMAIN|${{ secrets.FIREBASE_AUTH_DOMAIN }}|g" $FILE
          sed -i "s|GH_INJECT_PROJECT_ID|${{ secrets.FIREBASE_PROJECT_ID }}|g" $FILE
          sed -i "s|GH_INJECT_STORAGE_BUCKET|${{ secrets.STORAGEBUCKET }}|g" $FILE
          sed -i "s|GH_INJECT_SENDER_ID|${{ secrets.MESSAGINGSENDERID }}|g" $FILE
          sed -i "s|GH_INJECT_APP_ID|${{ secrets.FIREBASE_APP_ID }}|g" $FILE
          sed -i "s|GH_INJECT_MEASUREMENT_ID|${{ secrets.MEASUREMENTID }}|g" $FILE

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages